name: Continous Deployment

on:
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --prefer-offline

      - name: Run Lint
        run: yarn fe:lint

      - name: Run FrontEnd Build
        run: yarn fe:build

      - name: Run Tests
        run: yarn fe:test

      - name: Job was successfully executed! Hurray! 🥳
        if: success()
        run: echo "All steps executed successfully. Infer details from each step for further processing"

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build and Test Request Lambda
        run: yarn be:rl:build