name: Destroy Stack on AWS 🔴

on:
  workflow_dispatch:

permissions: write-all

jobs:
  destroy:
    runs-on: ubuntu-latest
    env: 
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --prefer-offline

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_AWS_ROLE }}
          aws-region: ap-south-1

      - name: Run FrontEnd Build
        run: yarn fe:build

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build Request Lambda
        run: yarn be:rl:build

      - name: Run Synth CDK
        run: yarn run cdk:synth

      - name: Destroy Stack
        run: yarn run cdk:destroy
